# Site settings
title: "My Website"
description: "My awesome website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Adam Lawson"
resume_title:                   ""

# used for the contact button in _layouts/resume.html
resume_contact_email:           "adamlawson@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "6136065783"
resume_contact_address:         ""

resume_header_contact_info:     " • 6136065783 • adamlawson@gmail.com"
display_header_contact_info:     

resume_header_intro: "I had an awesome career"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: 

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
resume_section_aboutme:       

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/adam99lawson"
  resume_linkedin_url:          "https://www.linkedin.com/in/adam99lawson"
  resume_website_url:           "adamlawson.dev"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
